const footballClubs = [
{ "club": "Arsenal",
  "details": {
    "Stadium": "Emirates Stadium",
    "capacity": "60,383 (all seated)",
    "address": "Highbury House, London, N5 1BU",
    "telephone": "020 7619 5003",
    "fax": "020 7704 4001",
    "ticket_office": "020 7619 5000",
    "stadium_tours": "020 7619 5000",
    "pitch_size": "105m x 68m",
    "pitch_type": "Grass",
    "club_nickname": "The Gunners",
    "year_ground_opened": "2006",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "Fly Emirates",
    "kit_manufacturer": "Puma",
    "home_kit": "Red and White",
    "away_kit": "Yellow and Blue",
    "reviews": []
  }
},
{ "club": "Aston Villa",
  "details": {
    "Stadium": "Villa Park",
    "capacity": "42,785 (all seated)",
    "address": "Trinity Road Birmingham B6 6HE",
    "telephone": "0121 327 2299",
    "fax": "0121 328 5575",
    "ticket_office": "0333 323 1874",
    "pitch_size": "115 x 72 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Villans",
    "year_ground_opened": "1897",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "W88",
    "kit_manufacturer": "Kappa",
    "home_kt": "Claret and Blue",
    "away_kit": "Light Blue and Claret",
    "reviews": []
  }
},
{ "club": "Bournemouth",
  "details": {
    "Stadium": "Vitality Stadium",
    "capacity": "11,329 (all seated)",
    "address": "Dean Court, Kings Park, Bournemouth, BH7 7AF",
    "telephone": "0844 576 1910",
    "fax": "01202 726373",
    "ticket_office": "0344 576 1910",
    "pitch_size": "115 x 71 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Cherries",
    "year_ground_opened": "1910",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "M88 Mansion",
    "kit_manufacturer": "Umbro",
    "home_kt": "Red & Black Stripes",
    "away_kit": "Dark Blue with Pink Trim",
    "reviews": []
  }
},
{ "club": "Brentford",
  "details": {
    "Stadium": "Brentford Community Stadium",
    "capacity": "17,250 (all seated)",
    "address": "Brentford Community Stadium, Lionel Road, London, England",
    "telephone": "0333 005 8521",
    "ticket_office": "0333 005 8521",
    "stadium_tours": "0333 005 8521",
    "pitch_size": "105m x 68m",
    "pitch_type": "Hybrid grass",
    "club_nickname": "The Bees",
    "year_ground_opened": "2020",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "Utilita Energy",
    "kit_manufacturer": "Umbro",
    "home_kt": "Red with White Stripes and Black Shorts",
    "away_kit": "Grey",
    "reviews": []
  }
},
{ "club": "Brighton & Hove Albion",
  "details": {
    "Stadium": "American Express Community Stadium",
    "capacity": "30,666 (all seated)",
    "address": "Village Way, Falmer, E Sussex, BN1 9BL",
    "telephone": "0344 324 6282",
    "fax": "01273 878238",
    "ticket_office": "0844 327 1901",
    "pitch_size": "115 x 75 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Seagulls",
    "year_ground_opened": "2011",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "American Express",
    "kit_manufacturer": "Nike",
    "home_kit": "Blue and White Stripes",
    "away_kit": "All Black",
    "reviews": []
  }
},
{ "club": "Chelsea",
  "details": {
    "Stadium": "Stanford Bridge", 
    "capacity": "41,631 (all seated)",
    "address": "Fulham Road, London, SW6 1HS",
    "telephone": "0371 811 1955",
    "fax": "020 7381 4831",
    "ticket_office": "0371 811 1905",
    "stadium_tours": "0371 811 1955",
    "pitch_size": "113 x 74 Yards",
    "pitch_type": "Grass",
    "club_nickname": "The Blues",
    "year_ground_opened": "1905",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "Yokohama Tyres",
    "kit_manufacturer": "Nike",
    "home_kt": "Royal Blue With White Trim",
    "away_kit": "White With Red & Blue Trim",
    "reviews": []
  }
},
{ "club": "Crystal Palace",
  "details": {
    "Stadium": "Selhurst Park",
    "capacity": "25,456 (all seated)",
    "address": "Selhurst Park, London, SE25 6PU",
    "telephone": "0208 768 6000",
    "fax": "0208 771 5311",
    "ticket_office": "0871 2000 071",
    "pitch_size": "110 x 74 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Eagles",
    "year_ground_opened": "1924",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "ManBetX",
    "kit_manufacturer": "Puma",
    "home_kit": "Red and Blue",
    "away_kit": "Black With Red & Blue",
    "reviews": []
  }
},
{ "club": "Everton",
  "details": {
    "Stadium": "Goodison Park",
    "capacity": "39,572 (all seated)",
    "address": "Goodison Road, Liverpool, L4 4EL",
    "telephone": "0151 556 1878",
    "fax": "0151 286 9112",
    "ticket_office": "0151 556 1878",
    "pitch_size": "112 x 78 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Toffees",
    "year_ground_opened": "1892",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "SportPesa",
    "kit_manufacturer": "Umbro",
    "home_kit": "Royal Blue & White",
    "away_kit": "Coral and Navy",
    "reviews": []
  }
},
{ "club": "Fulham",
  "details": {
    "Stadium": "Craven Cottage",
    "capacity": "19,000 (all seated)",
    "address": "Stevenage Road, London, SW6 6HH",
    "telephone": "0843 208 1222",
    "fax": "0207 384 4715",
    "ticket_office": "203 871 0810",
    "pitch_size": "109 x 71 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Cottagers or The Whites",
    "year_ground_opened": "1896",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "Dafabet",
    "kit_manufacturer": "Adidas",
    "home_kit": "White With Black Trim",
    "away_kit": "Red and White",
    "reviews": []
  }
},
{ "club": "Leeds United",
  "details": {
    "Stadium": "Elland Road",
    "capacity": "37,890 (all seated)",
    "address": "Elland Road, Leeds, LS11 0ES",
    "telephone": "0871 334 1919",
    "fax": "0113 367 6050",
    "ticket_office": "0371 334 1992",
    "pitch_size": "117 x 76 yards",
    "pitch_type": "Grass",
    "club_nickname": "United, Whites or Peacocks",
    "year_ground_opened": "1897",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "32Red",
    "kit_manufacturer": "Kappa",
    "home_kit": "White With Blue Trim",
    "away_kit": "Platinum with Pink Trim",
    "reviews": []
  }
},
{ "club": "Leicester City",
  "details": {
    "Stadium": "King Power Stadium",
    "capacity": "32,312 (all seated)",
    "address": "Filbert Way, Leicester, LE2 7FL",
    "telephone": "0344 815 5000",
    "fax": "0116 247 0585",
    "ticket_office": "0344 815 5000 (Option 1)",
    "pitch_size": "110 x 76 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Foxes",
    "year_ground_opened": "2002",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "King Power",
    "kit_manufacturer": "Adidas",
    "home_kit": "Blue and White",
    "away_kit": "Pink and Black",
    "reviews": []
  }
},
{ "club": "Liverpool",
  "details": {
    "Stadium": "Anfield",
    "capacity": "54,074 (all seated)",
    "address": "Anfield Road, Liverpool, L4 0TH",
    "telephone": "0151 264 2500",
    "fax": "0151 260 8813",
    "ticket_office": "0843 170 5555",
    "StadiumTours": "0151 260 6677",
    "pitch_size": "110 x 75 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Reds",
    "year_ground_opened": "1884",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "Standard Chartered",
    "kit_manufacturer": "New Balance",
    "home_kit": "All Red",
    "away_kit": "White & Navy Blue",
    "reviews": []
  }
},
{ "club": "Manchester City",
  "details": {
    "Stadium": "Etihad Stadium",
    "capacity": "55,097 (all seated)",
    "address": "Rowsley St, Manchester M11 3FF",
    "telephone": "0161 444 1894",
    "fax": "0161 438 7999",
    "ticket_office": "0161 444 1894",
    "StadiumTours": "0161 444 1894 (Option 4)",
    "pitch_size": "116 x 77 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Blues or Citizens",
    "year_ground_opened": "2002",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "Etihad Airways",
    "kit_manufacturer": "Puma",
    "home_kit": "Sky Blue and White",
    "away_kit": "All Black",
    "reviews": []
  }
},
{ "club": "Manchester United",
  "details": {
    "Stadium": "Old Trafford",
    "capacity": "74,879 (all seated)",
    "address": "Sir Matt Busby Way, Manchester M16 0RA",
    "telephone": "0161 868 8000",
    "fax": "0161 868 8804",
    "ticket_office": "0161 868 8000",
    "StadiumTours": "0161 868 8000",
    "pitch_size": "116 x 76 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Red Devils",
    "year_ground_opened": "1910",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "Chevrolet",
    "kit_manufacturer": "Adidas",
    "home_kit": "Red, White and Black",
    "away_kit": "White and Black",
    "reviews": []
  }
},
{ "club": "Newcastle United",
  "details": {
    "Stadium": "St James' Park",
    "capacity": "52,405 (all seated)",
    "address": "St. James' Park, Newcastle, NE1 4ST",
    "telephone": "0844 372 1892",
    "fax": "0191 201 8600",
    "ticket_office": "0844 372 1892 (Option 1)",
    "pitch_size": "115 x 74 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Magpies or The Toon",
    "year_ground_opened": "1892",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "FUN88",
    "kit_manufacturer": "Puma",
    "home_kit": "Black and White",
    "away_kit": "All Green",
    "reviews": []
  }
},
{ "club": "Nottingham Forest",
  "details": {
    "Stadium": "City Ground",
    "capacity": "30,445 (all seated)",
    "address": "City Ground, Nottingham, NG2 5FJ",
    "telephone": "0115 982 4444",
    "fax": "0115 982 4455",
    "ticket_office": "0115 982 4388",
    "pitch_size": "115 x 78 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Reds",
    "year_ground_opened": "1898",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "Football Index",
    "kit_manufacturer": "Macron",
    "home_kit": "Red and White",
    "away_kit": "Royal & Navy Blue Halves",
    "reviews": []
  }
},
{ "club": "Southampton",
  "details": {
    "Stadium": "St Mary's Stadium",
    "capacity": "32,505 (all seated)",
    "address": "Britannia Rd, Southampton, SO14 5FP",
    "telephone": "0845 688 9448",
    "fax": "0845 688 9445",
    "ticket_office": "02381 780 780",
    "pitch_size": "112 x 74 yards",
    "pitch_type": "Grass",
    "club_nickname": "The Saints",
    "year_ground_opened": "2001",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "LD Sports",
    "kit_manufacturer": "Under Armour",
    "home_kit": "Red, White & Black",
    "away_kit": "Grey & Yellow",
    "reviews": []
  }
},
{ "club": "Tottenham Hotspur",
  "details": {
    "Stadium": "Tottenham Hotspur Stadium",
    "capacity": "62,303 (all seated)",
    "address": "782 High Road, London, N17 0BX",
    "telephone": "0344 499 5000",
    "ticket_office": "0344 844 0102",
    "pitch_size": "115 x 74 yards",
    "pitch_type": "Grass",
    "club_nickname": "Spurs",
    "year_ground_opened": "2019",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "AIA",
    "kit_manufacturer": "Nike",
    "home_kit": "White and Navy",
    "away_kit": "Navy Blue",
    "reviews": []
  }
},
{ "club": "West Ham United",
  "details": {
    "Stadium": "London Stadium",
    "capacity": "60,000* (all seated)",
    "address": "Queen Elizabeth Olympic Park, E20 2ST",
    "telephone": "020 8548 2748",
    "ticket_office": "0333 030 1966",
    "pitch_size": "105m x 68m",
    "pitch_type": "Grass",
    "club_nickname": "The Hammers",
    "year_ground_opened": "2012",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "Betway",
    "kit_manufacturer": "Umbro",
    "home_kit": "Claret and Blue",
    "away_kit": "All White",
    "reviews": []
  }
},
{ "club": "Wolverhampton Wanderers",
  "details": {
    "Stadium": "Molineux",
    "capacity": "31,700 (all seated)",
    "address": "Waterloo Rd, Wolverhampton, WV1 4QR",
    "telephone": "0371 222 2220",
    "fax": "01902 687 006",
    "ticket_office": "0371 222 1877",
    "pitch_size": "116 x 74 yards",
    "pitch_type": "Grass",
    "club_nickname": "Wolves",
    "year_ground_opened": "1889",
    "undersoil_heating": "Yes",
    "shirt_sponsors": "ManBetX",
    "kit_manufacturer": "Adidas",
    "home_kit": "Gold and Black",
    "away_kit": "Black With Gold Trim",
    "reviews": []
  }
},
]
